"""initial schema

Revision ID: 2835de099915
Revises: 
Create Date: 2026-08-01 08:39:29.429431
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icai_registration_number', sa.String(length=64), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_types',
    sa.Column('firm_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('form_number', sa.String(length=32), nullable=True),
    sa.Column('statutory_reference', sa.String(length=255), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('due_month_offset', sa.Integer(), nullable=False),
    sa.Column('due_overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applicability_rule', sa.String(length=64), nullable=False),
    sa.Column('default_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('reminder_offsets_days', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'code', name='uq_compliance_type_firm_code')
    )
    op.create_index(op.f('ix_compliance_types_category'), 'compliance_types', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_types_code'), 'compliance_types', ['code'], unique=False)
    op.create_index(op.f('ix_compliance_types_firm_id'), 'compliance_types', ['firm_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('membership_number', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'email', name='uq_practitioner_firm_email')
    )
    op.create_index(op.f('ix_practitioners_email'), 'practitioners', ['email'], unique=False)
    op.create_index(op.f('ix_practitioners_firm_id'), 'practitioners', ['firm_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('firm_id', sa.Uuid(), nullable=True),
    sa.Column('actor_practitioner_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_practitioner_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_firm_created', 'audit_log', ['firm_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_practitioner_id'), 'audit_log', ['actor_practitioner_id'], unique=False)
    op.create_index(op.f('ix_audit_log_firm_id'), 'audit_log', ['firm_id'], unique=False)
    op.create_table('clients',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_practitioner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('tan', sa.String(length=10), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('gst_registered', sa.Boolean(), nullable=False),
    sa.Column('gst_filing_frequency', sa.String(length=16), nullable=False),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False),
    sa.Column('income_tax_applicable', sa.Boolean(), nullable=False),
    sa.Column('tax_audit_applicable', sa.Boolean(), nullable=False),
    sa.Column('roc_applicable', sa.Boolean(), nullable=False),
    sa.Column('payroll_applicable', sa.Boolean(), nullable=False),
    sa.Column('onboarded_on', sa.Date(), nullable=False),
    sa.Column('financial_year_start_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('service_fees', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_practitioner_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'pan', name='uq_client_firm_pan')
    )
    op.create_index('ix_client_firm_name', 'clients', ['firm_id', 'name'], unique=False)
    op.create_index(op.f('ix_clients_assigned_practitioner_id'), 'clients', ['assigned_practitioner_id'], unique=False)
    op.create_index(op.f('ix_clients_firm_id'), 'clients', ['firm_id'], unique=False)
    op.create_index(op.f('ix_clients_gstin'), 'clients', ['gstin'], unique=False)
    op.create_index(op.f('ix_clients_pan'), 'clients', ['pan'], unique=False)
    op.create_table('compliance_items',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_type_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_practitioner_id', sa.Uuid(), nullable=True),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('acknowledgement_number', sa.String(length=128), nullable=True),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('is_billed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_practitioner_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_type_id'], ['compliance_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'compliance_type_id', 'period_label', name='uq_compliance_item_period')
    )
    op.create_index('ix_compliance_item_firm_due', 'compliance_items', ['firm_id', 'due_date'], unique=False)
    op.create_index('ix_compliance_item_firm_status', 'compliance_items', ['firm_id', 'status'], unique=False)
    op.create_index('ix_compliance_item_period', 'compliance_items', ['firm_id', 'period_label'], unique=False)
    op.create_index(op.f('ix_compliance_items_assigned_practitioner_id'), 'compliance_items', ['assigned_practitioner_id'], unique=False)
    op.create_index(op.f('ix_compliance_items_client_id'), 'compliance_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_compliance_items_compliance_type_id'), 'compliance_items', ['compliance_type_id'], unique=False)
    op.create_index(op.f('ix_compliance_items_due_date'), 'compliance_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_compliance_items_firm_id'), 'compliance_items', ['firm_id'], unique=False)
    op.create_table('invoices',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_paise', sa.BigInteger(), nullable=False),
    sa.Column('gst_rate_bps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'invoice_number', name='uq_invoice_firm_number')
    )
    op.create_index('ix_invoice_firm_status', 'invoices', ['firm_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_firm_id'), 'invoices', ['firm_id'], unique=False)
    op.create_table('documents',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_item_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_practitioner_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('is_category_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extracted_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_practitioner_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_compliance_item_id'), 'documents', ['compliance_item_id'], unique=False)
    op.create_index(op.f('ix_documents_firm_id'), 'documents', ['firm_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_item_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('sac_code', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('reminders',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_item_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_firm_client', 'reminders', ['firm_id', 'client_id'], unique=False)
    op.create_index('ix_reminder_status_scheduled', 'reminders', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_reminders_client_id'), 'reminders', ['client_id'], unique=False)
    op.create_index(op.f('ix_reminders_compliance_item_id'), 'reminders', ['compliance_item_id'], unique=False)
    op.create_index(op.f('ix_reminders_firm_id'), 'reminders', ['firm_id'], unique=False)
    op.create_index(op.f('ix_reminders_invoice_id'), 'reminders', ['invoice_id'], unique=False)
    op.create_table('tasks',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('compliance_item_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_assignee_due', 'tasks', ['assignee_id', 'due_date'], unique=False)
    op.create_index('ix_task_firm_status', 'tasks', ['firm_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_compliance_item_id'), 'tasks', ['compliance_item_id'], unique=False)
    op.create_index(op.f('ix_tasks_firm_id'), 'tasks', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_firm_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_compliance_item_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index('ix_task_firm_status', table_name='tasks')
    op.drop_index('ix_task_assignee_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_reminders_invoice_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_firm_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_compliance_item_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_client_id'), table_name='reminders')
    op.drop_index('ix_reminder_status_scheduled', table_name='reminders')
    op.drop_index('ix_reminder_firm_client', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_documents_firm_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_compliance_item_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_invoices_firm_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index('ix_invoice_firm_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_compliance_items_firm_id'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_due_date'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_compliance_type_id'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_client_id'), table_name='compliance_items')
    op.drop_index(op.f('ix_compliance_items_assigned_practitioner_id'), table_name='compliance_items')
    op.drop_index('ix_compliance_item_period', table_name='compliance_items')
    op.drop_index('ix_compliance_item_firm_status', table_name='compliance_items')
    op.drop_index('ix_compliance_item_firm_due', table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index(op.f('ix_clients_pan'), table_name='clients')
    op.drop_index(op.f('ix_clients_gstin'), table_name='clients')
    op.drop_index(op.f('ix_clients_firm_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_assigned_practitioner_id'), table_name='clients')
    op.drop_index('ix_client_firm_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_log_firm_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_practitioner_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_firm_created', table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_practitioners_firm_id'), table_name='practitioners')
    op.drop_index(op.f('ix_practitioners_email'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_compliance_types_firm_id'), table_name='compliance_types')
    op.drop_index(op.f('ix_compliance_types_code'), table_name='compliance_types')
    op.drop_index(op.f('ix_compliance_types_category'), table_name='compliance_types')
    op.drop_table('compliance_types')
    op.drop_table('firms')
    # ### end Alembic commands ###
